#-Basic info----------------------------------------------------------------------------------------
display_name: chewbbaca
name: &name chewbbaca__v0_0_1__
version:
  schema: ["v2_1_0"]
  code: v0_0_1
  resource: ""
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This performs read based cgMLST with the chewbbaca suite https://github.com/B-UMMI/chewBBACA using
    either custom schemas or the ones provided with chewbbaca.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [chewbbaca]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_chewbbaca
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  chewbbaca_current_species: {Campylobacter jejuni,
                              Campylobacter coli,
                              Yersinia,
                              Escherichia coli,
                              Shigella,
                              Klebsiella,
                              Listeria monocytogenes,
                              Salmonella}
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  #schemes: "/bifrost/components/bifrost_cge_resfinder/resources/resfinder_db"
  #training_files: "/bifrost/components/bifrost_cge_resfinder/resources/pointfinder_db"
  schemes: "/bifrost_chewbbaca_schemes"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      paired_reads:
        summary:
          data:
      contigs:
        summary:
          data:
      species_detection:
        summary:
          detected_species:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      resistance:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      resistance:
        title: "chewbbaca"
        info: *name
        columns: 
          - {id: "phenotype", name: "phenotype"}
          - {id: "seq_regions", name: "seq_regions"}
          - {id: "amr_classes", name: "amr_classes"}
        data: []
  sample_component:
    summary:
      phenotypes: 
    results:
      cge_resfinder/resfinder_results/std_format.json: {}

#---------------------------------------------------------------------------------------------------
